spring:
  application:
    name: user-service
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2-console
      enabled: 'true'
  datasource:
    url: jdbc:h2:mem:ecom-db
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG

server:
  port: 8088

eureka:
  client:
    fetch-registry: 'true'
    register-with-eureka: 'true'
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: 'true'

syscho:
  openapi:
    url: http://localhost:8088


