version: '3'
services:

  service-discovery-server:
    build:
      context: ./service-discovery-server
    ports:
      - "8761:8761"  # Adjust the ports as needed
    networks:
      - mynetwork

  cart:
    build:
      context: ./cart
    ports:
      - "8086:8086"  # Adjust the ports as needed
    networks:
      - mynetwork
    depends_on:
      - service-discovery-server
      - woo-prometheus
      - woo-grafana
      - woo-zipkin 
    environment:
    - EUREKA_DEFAULT_ZONE=http://service-discovery-server:8761/eureka/ 
    - ZIPKIN_URL=http://zipkin:9411 

  product:
    build:
      context: ./products
    ports:
      - "8085:8085"  # Adjust the ports as needed
    networks:
      - mynetwork
    depends_on:
      - service-discovery-server
      - woo-prometheus
      - woo-grafana
      - woo-zipkin 
    environment:
    - EUREKA_DEFAULT_ZONE=http://service-discovery-server:8761/eureka/  
    - ZIPKIN_URL=http://zipkin:9411

  user:
    build:
      context: ./user
    ports:
      - "8088:8088"  # Adjust the ports as needed
    networks:
      - mynetwork
    depends_on:
      - service-discovery-server
      - woo-prometheus
      - woo-grafana
      - woo-zipkin 
    environment:
    - EUREKA_DEFAULT_ZONE=http://service-discovery-server:8761/eureka/  
    - ZIPKIN_URL=http://zipkin:9411

  order:
    build:
      context: ./order
    ports:
      - "8087:8087"  # Adjust the ports as needed
    networks:
      - mynetwork
    depends_on:
      - service-discovery-server
      - woo-prometheus
      - woo-grafana
      - woo-zipkin 
    environment:
    - EUREKA_DEFAULT_ZONE=http://service-discovery-server:8761/eureka/  
    - ZIPKIN_URL=http://zipkin:9411

  gateway:
    build:
      context: ./gateway
    ports:
      - "8091:8091"  # Adjust the ports as needed
    networks:
      - mynetwork
    depends_on:
      - service-discovery-server
      - woo-prometheus
      - woo-grafana
      - woo-zipkin 
    environment:
    - EUREKA_DEFAULT_ZONE=http://service-discovery-server:8761/eureka/  
    - ZIPKIN_URL=http://zipkin:9411

  woo-prometheus:
    image: prom/prometheus
    container_name: my-prometheus
    networks:
      - mynetwork
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped  


  woo-grafana:
    image: grafana/grafana-oss:latest
    container_name: my-grafana
    depends_on:
      - woo-prometheus
    networks:
      - mynetwork
    ports:
      - "3000:3000"
    restart: unless-stopped

  woo-zipkin:
    image: openzipkin/zipkin
    container_name: my-zipkin
    depends_on:
      - woo-prometheus
    networks:
      - mynetwork
    ports:
      - "9411:9411"
    restart: unless-stopped

networks:
  mynetwork:
    driver: bridge
    external: true
