spring:
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2-console
      enabled: 'true'
  datasource:
    url: jdbc:h2:mem:ecom-db
grpc:
  server:
    port: '8081'
  host: localhost
  client:
    products:
      address: localhost:8081
      negotiation-type: plaintext
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG

syscho:
  openapi:
    url: http://localhost:8080
