spring:
  application:
    name: product-service
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2-console
      enabled: 'true'
  datasource:
    url: jdbc:h2:mem:ecom-db

  zipkin:
    baseUrl:  ${ZIPKIN_URL:http://localhost:9411}

logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  include-application-name: false
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG

server:
  port: 8085

eureka:
  client:
    fetch-registry: 'true'
    register-with-eureka: 'true'
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: 'true'

management:
  tracing:
    sampling:
      probability: 1.0

  endpoints:
    web:
      exposure:
        include: '*'
      base-path: "/"
      path-mapping:
        prometheus: "metrics"


  metrics:
    enabled: true
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    tags:
      application: product-service


  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411}/api/v2/spans


syscho:
  openapi:
    url: http://localhost:8085




