spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          predicates:
            - Path=/api/users/**
          uri: http://localhost:8084
        - id: order-service
          predicates:
            - Path=/api/orders/**
          uri: http://localhost:8081
        - id: product-service
          predicates:
            - Path=/api/products/**
          uri: http://localhost:8087
        - id: cart-service
          predicates:
            - Path=/api/carts/**
          uri: http://localhost:8088

server:
  port: 8091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
