spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**

        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/carts/**
#Swagger Configuration
        - id: user-swagger
          uri: lb://user-service
          predicates:
            - Path=/v3/api-docs/**
            - Path=/swagger-ui/**

        - id: order-swagger
          uri: lb://order-service
          predicates:
            - Path=/order/v3/api-docs/**

        - id: product-swagger
          uri: lb://product-service
          predicates:
            - Path=/product/v3/api-docs/**

        - id: cart-swagger
          uri: lb://cart-service
          predicates:
            - Path=/cart/v3/api-docs/**

server:
  port: 8091

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
